site_name: dimi
repo_url: https://github.com/amyasnikov/dimi/
theme: material
nav:
  - Intro: index.md
  - DI Container API: di_api.md
  - Use Cases: use_cases.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
