site_name: dimi
repo_url: https://github.com/amyasnikov/dimi/
theme: material
nav:
  - Intro: index.md
  - DI Container API: di_api.md
  - Usage With Frameworks: web_usage.md
  - FAQ: faq.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
